# Generated by Django 3.2.5 on 2021-08-31 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, unique=True)),
                ('idTipoInstrumento', models.IntegerField(choices=[(-1, 'Corda'), (-2, 'Sopro'), (-3, 'Percussão'), (-4, 'Vocal')])),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('idTipoUsuario', models.IntegerField(choices=[(-1, 'Banda/Artista'), (-2, 'Empresa')])),
            ],
        ),
        migrations.CreateModel(
            name='BandaArtista',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='first_app.usuario')),
                ('numeroIntegrantes', models.IntegerField()),
                ('cpfOuCnpj', models.CharField(max_length=14, unique=True)),
                ('valorDataHora', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('first_app.usuario',),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='first_app.usuario')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
            ],
            bases=('first_app.usuario',),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPorteEvento', models.IntegerField(choices=[(-1, 'Grande'), (-2, 'Médio'), (-3, 'Pequeno')])),
                ('duracao', models.DurationField()),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('empresaAceitou', models.BooleanField()),
                ('bandaArtistaAceitou', models.BooleanField()),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.evento')),
                ('idBandaArtisata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.bandaartista')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='BandaArtistaInstrumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInstrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.instrumento')),
                ('idBandaArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.bandaartista')),
            ],
        ),
        migrations.CreateModel(
            name='BandaArtistaGeneroDeApresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGeneroMusical', models.IntegerField(choices=[(-1, 'Rock'), (-2, 'Sertanejo'), (-3, 'Pop'), (-4, 'Casamento'), (-5, 'Samba'), (-6, 'Pagode')])),
                ('idBandaArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.bandaartista')),
            ],
        ),
        migrations.CreateModel(
            name='BandaArtistaArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathArquivo', models.CharField(max_length=300, unique=True)),
                ('idBandaArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.bandaartista')),
            ],
        ),
    ]
