# Generated by Django 3.2.5 on 2021-11-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.IntegerField()),
                ('generosMusicais', models.IntegerField()),
                ('valorDataHora', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoMineracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maiorTendencia', models.IntegerField()),
                ('menorTendencia', models.IntegerField()),
                ('valorDataHora', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='idStatus',
            field=models.IntegerField(choices=[(-1, 'Encerrado'), (-2, 'Cancelado'), (-3, 'Aguandando aprovação'), (-4, 'Em vigor')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='idStatus',
            field=models.IntegerField(choices=[(-1, 'Encerrado'), (-2, 'Cancelado'), (-3, 'Agendado'), (-4, 'Em vigor')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
