# Generated by Django 3.2.5 on 2021-11-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20211108_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='valorDataHora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resultadomineracao',
            name='valorDataHora',
            field=models.DateTimeField(),
        ),
    ]
