# Generated by Django 3.2.5 on 2021-11-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20211108_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupom',
            name='generosMusicais',
        ),
        migrations.AddField(
            model_name='cupom',
            name='generoMusical',
            field=models.IntegerField(choices=[(-1, 'Rock'), (-2, 'Sertanejo'), (-3, 'Pop'), (-4, 'Samba'), (-5, 'Pagode'), (-6, 'Funk')], default=0),
            preserve_default=False,
        ),
    ]
