# Generated by Django 3.2.5 on 2021-11-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20211109_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='idBandaArtisata',
            new_name='idBandaArtista',
        ),
        migrations.AlterField(
            model_name='evento',
            name='duracao',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
